services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: hirehub-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=tdbrjefi
      - RABBITMQ_DEFAULT_PASS=QxL6Fkag7ufwn4tyT8bBTEz2wipKT_pu
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: hirehub-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  rabbitmq_data:
  redis_data: